version: '3'

services:
  monitor:
    image: monitor:latest
    ports:
      - "11100:11100"
    environment:
      - PORT=11100
      - ALLOW_ORIGIN=*
    restart: always
    volumes:
      - ./logs:/app/logs
